apiVersion: v1
kind: Template
labels:
  template: projectrequest-template
message: 'Project/Namespace has been created: ${NAMESPACE}'
metadata:
  annotations:
    description: ProjectRequest Template
  creationTimestamp: null
  name: projectrequest-template
objects:
- apiVersion: v1
  description: ${NAMESPACE_DESCRIPTION}
  displayName: ${NAMESPACE_DISPLAY_NAME}
  kind: ProjectRequest
  metadata:
    name: ${NAMESPACE}
parameters:
- description: Name
  displayName: Name
  name: NAMESPACE
  required: true
- description: DisplayName
  displayName: DisplayName
  name: NAMESPACE_DISPLAY_NAME
  required: true
- description: Description
  displayName: Description
  name: NAMESPACE_DESCRIPTION
