---
ansible_connection: local

openshift_cluster_content:
- object: projects
  content:
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/project"
    tags:
    - projectrequests
    - projectrequests-dev 
- object: ruby-components
  content:
  - name: ruby-ex
    template: "{{ playbook_dir }}/templates/app/ruby.yml"
    params: "{{ playbook_dir }}/params/ruby/build"
    namespace: "ruby-example"
    tags:
    - app
